apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-image-deployment
  labels:
    app: nodejs-image
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nodejs-image
  template:
    metadata:
      labels:
        app: nodejs-image 
    spec:
      containers:
        - name: nodejs-image
          image: babu8050796070/nodejs-image-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1 
kind: Service 
metadata: 
  name: nodejs-image-svc
spec:
  selector:
    app: nodejs-image
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
  type: NodePort 


   this is demo 
  
